name: Build Springboot Backend

on:
  push:
    branches: [ main ]

env:
  JAVA_VERSION: 17

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Gradle Build
        run: |
          ./gradlew build build
        working-directory: ./backend-springboot-java
          

